---
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
env:
  - COVERAGE=1

script:
  - bin/rubocop
  - bin/rspec --format doc

jobs:
  include:
    - stage: release
      rvm: 2.3
      script: skip
      deploy:
        provider: rubygems
        api_key:
          secure: 'tu+TzDHhiKVy5EeiMb8NVb/EHSflqhAhie6OFJc72nBBFAF9mow71sFpOzleQJ0gNdKnrWf17AQZLO9UQLIY2gP6fOHrLfDO5yLBMEpMjoqZISSBtugNUNCf8vg37QWbG6mAzMM67I/dMqT7U9KgL8CwaUwrs75W4KmIoaYqzkjiLc++k9j9dKpdbBBCEp0KNNbuAfEc9YWoas45LWFR1VfqB0CaGX4z8kWZai+N+8JLsmEO2bK6bPp2wtE+5ofXdkr5vSZK9Sp/7vLmh7P/D6ZDvuaF8KPt3wuPdtS1ZebuGWLsExcTTIgXzWBcYQ3hSHpvOwLWhI0M8ZpxmO3PPZO8+LsAzBijCj1HyOaXIrIybebuapvRixjWEV6mk3UXpBWgS3u0dslfbYa9hzbKCtAN/MTDSwLkdSuxsTuonNd406QQvX9O+yNT5+N8QpBqlAONeurSZhIRioiIyAwu6fL1CIJ5muDPaqG/V+dCh+z3W5KqnKgr9dY/bN8XizQoZhEFPg8WUjG2/ZRwtw3u5BD1rCbJIt3tAUSwhLLoSQFkH1f07evOuArOzaJjmehdaOiERkzsVmip65F/Bt+03NYShNzw3qK416ZjoxvVXpgb+mHVB8TEHL11bmvnrJ/v//fRp2W0ClHDZBmHvuem3UIXb7vnDDtvn8HClNHlgkg='
        gem: uncsv
        on:
          tags: true
          condition: bin/check-version
      repo: machinima/uncsv

# after_success:
#   - bin/codeclimate-test-reporter

# addons:
#   code_climate:
#     repo_token:
#       secure: ""
